-- ═══════════════════════════════════════════════════════════════════════════
--  034_catalogo_con_acentos.sql — H4 · La Bóveda: el catálogo, bien escrito
--
--  QUÉ ARREGLA.
--
--  El seed de la 033 se escribió entero sin un solo acento. Las 109 cadenas
--  del catálogo —las cinco taxonomías por giro— salen TAL CUAL en la pantalla
--  del cliente: son los títulos y las pistas de «qué le falta a tu negocio» en
--  /direccion, y el vocabulario con el que el agente maestro pregunta.
--
--  Lo que leía el invitado del ensayo del 2026-07-31, verificado en producción:
--
--      Cotizacion · Politica de envios · Garantia y devoluciones
--      Que entra, que sale y cuanto queda.
--      En tus palabras: que vendes, a quien y por que a ti
--      ...marketing, diseno, software, contabilidad.
--
--  No es jerga: es peor. La jerga se lee como "esto no es para mí"; esto se lee
--  como "esto está mal hecho". Y «diseno» en la descripción de un giro, en un
--  producto para PyME mexicana, es una errata que se ve desde la puerta.
--
--  QUÉ NO CAMBIA. Ni una llave, ni un `slug`, ni un `doc_type`, ni un `kind`:
--  esos son identificadores y `detectGaps()` los compara contra lo que el
--  tenant tiene. Sólo cambian `name`, `blurb` y los campos `label`, `title`,
--  `hint` y `blurb` de dentro del JSON — es decir, exactamente lo que se pinta.
--
--  POR QUÉ UNA MIGRACIÓN NUEVA Y NO UNA CORRECCIÓN DE LA 033. Porque la 033 ya
--  está aplicada y con checksum; editarla haría fallar al runner en cualquier
--  entorno que ya la tenga. Esto es idempotente: se puede correr las veces que
--  haga falta y deja siempre el mismo texto.
--
--  Sin cambios de esquema, sin tablas nuevas, sin RLS que tocar. Sólo datos de
--  un catálogo de plataforma (`tenantless`, ver la 033).
-- ═══════════════════════════════════════════════════════════════════════════

UPDATE app.industry_templates SET
  name            = 'Servicios profesionales',
  blurb           = 'Despachos, consultorios, talleres, salones, estudios. Cobras por tu trabajo o por hora.',
  areas           = '[{"icon":"Target","slug":"ventas","blurb":"De la primera llamada al sí. Cotizaciones, seguimiento y cierre.","label":"Ventas","position":1},{"icon":"Wrench","slug":"operaciones","blurb":"Cómo se entrega el servicio: agenda, proceso y estándar de calidad.","label":"Operaciones","position":2},{"icon":"HeartHandshake","slug":"servicio","blurb":"Post-venta, quejas, garantías y recompra.","label":"Atención a clientes","position":3},{"icon":"Wallet","slug":"finanzas","blurb":"Ingresos, gastos, margen y lo que le debes al SAT.","label":"Finanzas","position":4},{"icon":"Compass","slug":"direccion","blurb":"Tu bóveda: los números, los documentos y la biblioteca del negocio.","label":"Dirección","position":9}]'::jsonb,
  expected_docs   = '[{"hint":"Cuánto cobras por cada servicio","title":"Lista de precios y paquetes","doc_type":"precios","area_slug":"ventas"},{"title":"Guion de la primera llamada","doc_type":"guion","area_slug":"ventas"},{"hint":"El machote que mandas; puede usar {valor.*}","title":"Cotización","doc_type":"plantilla","area_slug":"ventas"},{"title":"Objeciones frecuentes","doc_type":"faq","area_slug":"ventas"},{"hint":"Paso a paso, de la contratación a la entrega","title":"Cómo se entrega el servicio","doc_type":"sop","area_slug":"operaciones"},{"title":"Política de agenda y cancelaciones","doc_type":"politica","area_slug":"operaciones"},{"title":"Garantía y devoluciones","doc_type":"politica","area_slug":"servicio"},{"title":"Formas de pago y facturación","doc_type":"politica","area_slug":"finanzas"},{"hint":"En tus palabras: qué vendes, a quién y por qué a ti","title":"A qué se dedica el negocio","doc_type":"otro","area_slug":"direccion"}]'::jsonb,
  expected_values = '[{"key":"ticket_promedio","hint":"Cuánto deja en promedio un cliente","kind":"money","area_slug":"ventas"},{"key":"precio_hora","hint":"Si cobras por hora","kind":"money","area_slug":"ventas"},{"key":"anticipo_pct","hint":"Qué porcentaje pides por adelantado","kind":"percent","area_slug":"ventas"},{"key":"primer_contacto_max_horas","hint":"En cuántas horas contestas un prospecto nuevo","kind":"number","area_slug":"ventas"},{"key":"tiempo_entrega_dias","kind":"number","area_slug":"operaciones"},{"key":"horario_atencion","hint":"Ej. lunes a viernes de 9 a 6","kind":"text","area_slug":"operaciones"},{"key":"capacidad_semanal","hint":"Cuántos clientes o proyectos aguantas por semana","kind":"number","area_slug":"operaciones"},{"key":"garantia_meses","kind":"number","area_slug":"servicio"},{"key":"iva_pct","hint":"16 en México","kind":"percent","area_slug":"finanzas"},{"key":"margen_objetivo_pct","kind":"percent","area_slug":"finanzas"},{"key":"dias_credito","hint":"Cuántos días le das a un cliente para pagar","kind":"number","area_slug":"finanzas"},{"key":"gasto_fijo_mensual","hint":"Renta, nómina y servicios: lo que se paga vendas o no","kind":"money","area_slug":"finanzas"}]'::jsonb
WHERE id = 'servicios';

UPDATE app.industry_templates SET
  name            = 'Comercio y tienda en línea',
  blurb           = 'Vendes producto: local, tienda en línea, marketplace o las tres.',
  areas           = '[{"icon":"Target","slug":"ventas","blurb":"Mostrador, pedidos y carrito. De la pregunta a la compra.","label":"Ventas","position":1},{"icon":"Megaphone","slug":"marketing","blurb":"Cómo te encuentran: contenido, pauta, redes y promociones.","label":"Marketing","position":2},{"icon":"Boxes","slug":"inventario","blurb":"Qué tienes, qué se acaba, a quién le compras y a cómo.","label":"Inventario","position":3},{"icon":"HeartHandshake","slug":"servicio","blurb":"Envíos, cambios, devoluciones y garantías.","label":"Atención a clientes","position":4},{"icon":"Wallet","slug":"finanzas","blurb":"Margen por producto, gastos e impuestos.","label":"Finanzas","position":5},{"icon":"Compass","slug":"direccion","blurb":"Tu bóveda: los números, los documentos y la biblioteca del negocio.","label":"Dirección","position":9}]'::jsonb,
  expected_docs   = '[{"hint":"Producto por producto, con su costo","title":"Lista de precios","doc_type":"precios","area_slug":"ventas"},{"hint":"Lo que contestas a «¿está disponible?» y «¿cuánto cuesta?»","title":"Respuestas de venta por WhatsApp","doc_type":"guion","area_slug":"ventas"},{"title":"Calendario de publicaciones","doc_type":"sop","area_slug":"marketing"},{"hint":"Logo, colores y tono","title":"Identidad de marca","doc_type":"manual","area_slug":"marketing"},{"title":"Proveedores y tiempos de resurtido","doc_type":"politica","area_slug":"inventario"},{"title":"Control de inventario y mermas","doc_type":"sop","area_slug":"inventario"},{"hint":"Costo, zonas y tiempos","title":"Política de envíos","doc_type":"politica","area_slug":"servicio"},{"title":"Cambios y devoluciones","doc_type":"politica","area_slug":"servicio"},{"title":"Formas de pago y facturación","doc_type":"politica","area_slug":"finanzas"},{"title":"A qué se dedica el negocio","doc_type":"otro","area_slug":"direccion"}]'::jsonb,
  expected_values = '[{"key":"ticket_promedio","kind":"money","area_slug":"ventas"},{"key":"descuento_maximo_pct","hint":"Hasta dónde puede bajar quien vende sin pedir permiso","kind":"percent","area_slug":"ventas"},{"key":"presupuesto_pauta_mensual","kind":"money","area_slug":"marketing"},{"key":"canales_activos","hint":"Ej. Instagram, WhatsApp, Mercado Libre","kind":"list","area_slug":"marketing"},{"key":"stock_minimo","hint":"Cuándo se resurte","kind":"number","area_slug":"inventario"},{"key":"merma_max_pct","kind":"percent","area_slug":"inventario"},{"key":"dias_resurtido","kind":"number","area_slug":"inventario"},{"key":"costo_envio","kind":"money","area_slug":"servicio"},{"key":"envio_gratis_desde","kind":"money","area_slug":"servicio"},{"key":"dias_devolucion","kind":"number","area_slug":"servicio"},{"key":"iva_pct","hint":"16 en México","kind":"percent","area_slug":"finanzas"},{"key":"margen_objetivo_pct","kind":"percent","area_slug":"finanzas"},{"key":"gasto_fijo_mensual","kind":"money","area_slug":"finanzas"}]'::jsonb
WHERE id = 'comercio';

UPDATE app.industry_templates SET
  name            = 'Restaurante y cafetería',
  blurb           = 'Cocinas y vendes en el momento: local, para llevar o reparto.',
  areas           = '[{"icon":"Store","slug":"ventas","blurb":"Menú, precios, pedidos y apps de reparto.","label":"Ventas y piso","position":1},{"icon":"ChefHat","slug":"operaciones","blurb":"Recetas, tiempos, higiene y cómo se abre y se cierra.","label":"Cocina y operación","position":2},{"icon":"Boxes","slug":"inventario","blurb":"Proveedores, costo por platillo y merma.","label":"Insumos","position":3},{"icon":"Megaphone","slug":"marketing","blurb":"Cómo llenas el local: redes, reseñas y promociones.","label":"Marketing","position":4},{"icon":"Wallet","slug":"finanzas","blurb":"Costo de venta, nómina, renta y punto de equilibrio.","label":"Finanzas","position":5},{"icon":"Compass","slug":"direccion","blurb":"Tu bóveda: los números, los documentos y la biblioteca del negocio.","label":"Dirección","position":9}]'::jsonb,
  expected_docs   = '[{"title":"Menú con precios","doc_type":"precios","area_slug":"ventas"},{"title":"Política de reservaciones y reparto","doc_type":"politica","area_slug":"ventas"},{"hint":"Gramaje por platillo: es de donde sale el costo real","title":"Recetario","doc_type":"manual","area_slug":"operaciones"},{"title":"Apertura y cierre del local","doc_type":"sop","area_slug":"operaciones"},{"title":"Higiene y manejo de alimentos","doc_type":"sop","area_slug":"operaciones"},{"title":"Proveedores y días de pedido","doc_type":"politica","area_slug":"inventario"},{"title":"Calendario de publicaciones","doc_type":"sop","area_slug":"marketing"},{"title":"Costeo por platillo","doc_type":"precios","area_slug":"finanzas"},{"title":"A qué se dedica el negocio","doc_type":"otro","area_slug":"direccion"}]'::jsonb,
  expected_values = '[{"key":"ticket_promedio","kind":"money","area_slug":"ventas"},{"key":"horario_atencion","kind":"text","area_slug":"ventas"},{"key":"comision_app_reparto_pct","hint":"Lo que se queda Rappi, Uber Eats o DiDi","kind":"percent","area_slug":"ventas"},{"key":"tiempo_preparacion_min","kind":"number","area_slug":"operaciones"},{"key":"aforo","hint":"Cuántos comensales caben","kind":"number","area_slug":"operaciones"},{"key":"costo_insumos_pct","hint":"Costo de venta sobre el precio; sano ronda 30","kind":"percent","area_slug":"inventario"},{"key":"merma_max_pct","kind":"percent","area_slug":"inventario"},{"key":"iva_pct","hint":"16 en México","kind":"percent","area_slug":"finanzas"},{"key":"renta_mensual","kind":"money","area_slug":"finanzas"},{"key":"nomina_mensual","kind":"money","area_slug":"finanzas"},{"key":"punto_equilibrio_mensual","hint":"Cuánto tienes que vender al mes para no perder","kind":"money","area_slug":"finanzas"}]'::jsonb
WHERE id = 'restaurante';

UPDATE app.industry_templates SET
  name            = 'Agencia o estudio',
  blurb           = 'Vendes trabajo por proyecto o por iguala: marketing, diseño, software, contabilidad.',
  areas           = '[{"icon":"Target","slug":"ventas","blurb":"Propuestas, igualas y cierre de cuentas nuevas.","label":"Ventas","position":1},{"icon":"Megaphone","slug":"marketing","blurb":"Tu propia demanda: portafolio, contenido y referidos.","label":"Marketing propio","position":2},{"icon":"HeartHandshake","slug":"servicio","blurb":"Clientes activos: entregables, juntas y reportes.","label":"Cuentas","position":3},{"icon":"Wrench","slug":"operaciones","blurb":"Cómo se produce el trabajo: flujo, revisiones y entrega.","label":"Producción","position":4},{"icon":"Wallet","slug":"finanzas","blurb":"Rentabilidad por cuenta, cobranza y costo por hora.","label":"Finanzas","position":5},{"icon":"Compass","slug":"direccion","blurb":"Tu bóveda: los números, los documentos y la biblioteca del negocio.","label":"Dirección","position":9}]'::jsonb,
  expected_docs   = '[{"title":"Tabulador de servicios e igualas","doc_type":"precios","area_slug":"ventas"},{"title":"Propuesta comercial","doc_type":"plantilla","area_slug":"ventas"},{"hint":"Machote renderizable con {valor.*}","title":"Contrato de prestación de servicios","doc_type":"contrato","area_slug":"ventas"},{"title":"Objeciones frecuentes","doc_type":"faq","area_slug":"ventas"},{"hint":"De la firma a la primera entrega","title":"Alta de cliente nuevo","doc_type":"sop","area_slug":"servicio"},{"title":"Reporte mensual de resultados","doc_type":"plantilla","area_slug":"servicio"},{"hint":"Cuántas rondas de cambios entran en el precio","title":"Flujo de producción y revisiones","doc_type":"sop","area_slug":"operaciones"},{"title":"Cobranza y penalización por atraso","doc_type":"politica","area_slug":"finanzas"},{"title":"A qué se dedica el negocio","doc_type":"otro","area_slug":"direccion"}]'::jsonb,
  expected_values = '[{"key":"iguala_mensual_minima","kind":"money","area_slug":"ventas"},{"key":"precio_hora","kind":"money","area_slug":"ventas"},{"key":"anticipo_pct","kind":"percent","area_slug":"ventas"},{"key":"comision_vendedor_pct","kind":"percent","area_slug":"ventas"},{"key":"rondas_revision_incluidas","hint":"De aquí salen casi todos los pleitos con clientes","kind":"number","area_slug":"servicio"},{"key":"tiempo_respuesta_horas","kind":"number","area_slug":"servicio"},{"key":"capacidad_proyectos_simultaneos","kind":"number","area_slug":"operaciones"},{"key":"iva_pct","hint":"16 en México","kind":"percent","area_slug":"finanzas"},{"key":"retencion_isr_pct","hint":"Si facturas a persona moral","kind":"percent","area_slug":"finanzas"},{"key":"dias_credito","kind":"number","area_slug":"finanzas"},{"key":"margen_objetivo_pct","kind":"percent","area_slug":"finanzas"},{"key":"gasto_fijo_mensual","kind":"money","area_slug":"finanzas"}]'::jsonb
WHERE id = 'agencia';

UPDATE app.industry_templates SET
  name            = 'Otro giro',
  blurb           = 'Lo mínimo que todo negocio necesita tener claro, sea cual sea su giro.',
  areas           = '[{"icon":"Target","slug":"ventas","blurb":"Cómo llega un cliente y cómo se cierra la venta.","label":"Ventas","position":1},{"icon":"Wrench","slug":"operaciones","blurb":"Cómo se entrega lo que vendes.","label":"Operaciones","position":2},{"icon":"Wallet","slug":"finanzas","blurb":"Qué entra, qué sale y cuánto queda.","label":"Finanzas","position":3},{"icon":"Compass","slug":"direccion","blurb":"Tu bóveda: los números, los documentos y la biblioteca del negocio.","label":"Dirección","position":9}]'::jsonb,
  expected_docs   = '[{"title":"Lista de precios","doc_type":"precios","area_slug":"ventas"},{"title":"Qué le dices a un cliente nuevo","doc_type":"guion","area_slug":"ventas"},{"title":"Cómo se entrega lo que vendes","doc_type":"sop","area_slug":"operaciones"},{"title":"Formas de pago y facturación","doc_type":"politica","area_slug":"finanzas"},{"hint":"En tus palabras: qué vendes, a quién y por qué a ti","title":"A qué se dedica el negocio","doc_type":"otro","area_slug":"direccion"}]'::jsonb,
  expected_values = '[{"key":"ticket_promedio","kind":"money","area_slug":"ventas"},{"key":"horario_atencion","kind":"text","area_slug":"ventas"},{"key":"tiempo_entrega_dias","kind":"number","area_slug":"operaciones"},{"key":"iva_pct","hint":"16 en México","kind":"percent","area_slug":"finanzas"},{"key":"margen_objetivo_pct","kind":"percent","area_slug":"finanzas"},{"key":"gasto_fijo_mensual","kind":"money","area_slug":"finanzas"}]'::jsonb
WHERE id = 'general';
